# Server port
server:
  port: 9010

# Giving a name to our message service
spring:
  application:
    name: "message"
  cloud:
    function:
      definition: email|sms
    stream:
      bindings:
        emailsms-in-0: # Input binding
          destination: send-communication # Queue name
          group: ${spring.application.name} # Suffix for queue name to ensure it is unique and prevent random generation of suffix values to our queue
        emailsms-out-0: # Output binding
          destination: communication-sent # The exchange name. With the help of this, messages/events/notifications from message ms' emailsms function will be sent to this exchange.
      kafka:
        binder:
          brokers: # If you have multiple kafka brokers running inside a cluster you can try to mention all of them as a list of elements under the 'brokers' element.
            - localhost:9092