package com.get_tt_right.gwserver.config;

import com.get_tt_right.gwserver.service.client.CustomerSummaryClient;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.web.reactive.function.client.WebClient;
import org.springframework.web.reactive.function.client.support.WebClientAdapter;
import org.springframework.web.service.invoker.HttpServiceProxyFactory;

/** On top of this class we are mentioning the @Configuration annotation because this is a configuration class.
 * Followed by I am going to create a private primary attribute i.e., baseUrl of type String. This baseUrl value we want to read from the properties file so that we can change this value dynamically across various environments. That's why we are trying o use @Value annotation. To this value annotation I am going to mention the variable value as 'app.base-url'
 * As a next step, open the yaml file of gatewayserver and mention/define a property app.base-url and to it assign the value http://localhost:8070. This is what we are trying to refer from ClientConfig using the @Value annotation. Now, we have provided the base url details to the client config class. Now after that private primary field, we are going to create a method named customerClient with the @Bean annotation on top of it. This method is going to return the object of CustomerSummaryClient interface that we have created previously. This method is not going to accept anything as an input.
 * Inside this method, first we want to create the object of WebClient by invoking the WebClient.builder().baseUrl(baseUrl).build(); As you can see to the baseUrl method we are passing the baseUrl field name followed by we need to invoke the build() method. Now, we have WebClient object which is aware of base url. Once this WebClient object is created, we want to wrap is with the help of WebClientAdapter by invoking the WebClientAdapter create static method and to this create method we are passing the object of WebClient as an input. Basically we are trying to wrap the WebClient object into the WebClientAdapter and the result we are storing into a variable named adapter of type WebClientAdapter.
 * Why are we trying to wrap this WebClient object into WebClientAdapter?
 * Next, we are trying to create the object of HttpServiceProxyFactory by invoking builderFor method. To this builderFor we are going to pass the WebClientAdapter object as an input and finally invoking the build method. At last, I am trying to return the object of CustomerSummaryClient by writing the code which is factory.createClient(-) and to this createClient method I am going to pass the CustomerSummaryClient interface information as an input.
 * Basically, what the last 3 lines in the customerClient method are doing is - inside our interface - CustomerSummeryClient - we only defined abstract methods in a declarative style. Nothing but we have not defined any implementation code on how these ms's should be invoked and so, all the proxy implementations of these http interfaces (The abstract methods) are going to be generated by the HttpServiceProxyFactory but to this factory object method i.e., builderFor, we need to pass the object of type HttpExchangeAdaptor. Since this builderFor method is not going to accept the WebClient object as an input, so, we are going to wrap the WebClient object by using a utility tool which is WebClientAdapter and on top of it invoking the create method and to this create method we are passing the WebClient object as an input. By the time this create method executes it is going to return us a WebClientAdapter object which if you navigate to the WebClientAdapter, you will notice it extends AbstractReactorHttpExchangeAdaptor which if you navigate further into it, you will notice that it is implementing ReactorHttpExchangeAdaptor and at last if you navigate to the ReactorHttpExchangeAdaptor, you will notice it is extending HttpExchangeAdaptor.
 * Basically, with the help of this WebClientAdapter we are making our WebClient object ready to be used by other framework classes like HttpServiceProxyFactory. With this you should be crisp clear now on why we are trying to wrap the WebClient object into WebClientAdapter.
 * So, with the help of this customerClient method we are trying to generate the actual implementation of all the actual declarative methods that we have defined inside the CustomerSummaryClient interface. So, my WebClient has the base url information and my HttpServiceProxyFactory it has all the metadata information and inside this metadata we have provided actual path that the WebClient can use to invoke so-and-so ms with the mentioned behavior signature i.e., inputs and expected responses.
 * With all we have discussed you should be now clear on why we have created this ClientConfig class.
 * */
@Configuration
public class ClientConfig {

    @Value("${app.base-url}")
    private String baseUrl;

    @Bean
    CustomerSummaryClient customerClient() {
        WebClient webClient = WebClient.builder().baseUrl(baseUrl).build();
        WebClientAdapter adapter = WebClientAdapter.create(webClient);
        HttpServiceProxyFactory factory = HttpServiceProxyFactory.builderFor(adapter).build();
        return factory.createClient(CustomerSummaryClient.class);
    }

}