#spring.application.name=accounts
server:
  port: 8080
spring:
  application:
    name: accounts
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
# Telling to the Spring boot framework to enable the h2 console so that I can log into it from my browser.
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    import:
# Since we are mentioning a list of elements, they should start with a hyphen (-) followed by a space then value(In this case the profile/ yaml file names).
      - "application_qa.yml"
      - "application_prod.yml"
  profiles:
    active:
      - "prod"

# As of now we have made the below configurations inside this Accounts service.
build:
  version: "3.0"

accounts:
  message: "Welcome to EazyBank accounts related local APIs "
  contactDetails:
    name: "John Doe - Developer"
    email: "john@eazybank.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345