spring:
  application:
    name: "gatewayserver"

  config:
    import: 'optional:configserver:http://localhost:8071'

  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lowerCaseServiceId: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    gateway:
      enabled: true
  info:
    env:
      enabled: true

info:
  app:
    name: "gatewayserver"
    description: "Eazy Bank Gatewayserver Application"
    version: "1.0.0"

# With this configuration, the logging level for the com.get_tt_right.gwserver package will be set to DEBUG. Which means, all the logs related to this package and are of level DEBUG will be printed.
logging:
  level:
    com:
      get_tt_right:
        gwserver: DEBUG
