services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping | grep PONG" ]
      timeout: 10s
      retries: 10
    extends:
      file: common-config.yml
      service: network-deploy-service

  accountsdb:
    container_name: accountsdb
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: "accountsdb"
    extends:
      file: 'common-config.yml'
      service: 'microservice-db-config'

  loansdb:
    container_name: loansdb
    ports:
      - "3309:3306"
    environment:
      MYSQL_DATABASE: "loansdb"
    extends:
      file: 'common-config.yml'
      service: 'microservice-db-config'

  cardsdb:
    container_name: cardsdb
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: "cardsdb"
    extends:
      file: 'common-config.yml'
      service: 'microservice-db-config'

  rabbit:
    image: rabbitmq:4.0-management
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s
    extends:
      file: 'common-config.yml'
      service: 'network-deploy-service'

  eurekaserver:
    image: "colince819/eurekaserver:v1"
    container_name: eurekaserver-ms
    ports:
      - "8070:8070"
    depends_on:
      rabbit:
        condition: service_healthy
      cofigserver:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "eurekaserver"
    healthcheck:
      test: 'curl --fail --silent http://localhost:8070/actuator/health/readiness | grep "UP" || exit 1'
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: 'common-config.yml'
      service: 'microservice-configserver-config'

  cofigserver:
    image: "colince819/configserver:v1"
    container_name: configserver-ms
    ports:
      - "8071:8071"
    depends_on:
      rabbit:
        condition: service_healthy
    healthcheck:
      test: 'curl --fail --silent http://localhost:8071/actuator/health/readiness | grep "UP" || exit 1'
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: 'common-config.yml'
      service: 'microservice-base-config'

  accounts:
    image: "colince819/accounts:v6"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    healthcheck:
      test: 'curl --fail --silent http://localhost:8080/actuator/health/readiness | grep "UP" || exit 1'
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    depends_on:
      cofigserver:
        condition: 'service_healthy'
      accountsdb:
        condition: 'service_healthy'
    environment:
      SPRING_APPLICATION_NAME: "accounts"
      SPRING_DATASOURCE_URL: "jdbc:mysql://accountsdb:3306/accountsdb"
    extends:
      file: 'common-config.yml'
      service: 'microservice-eureka-config'

  loans:
    image: "colince819/loans:v6"
    container_name: loans-ms
    ports:
      - "8090:8090"
    healthcheck:
      test: 'curl --fail --silent http://localhost:8090/actuator/health/readiness | grep "UP" || exit 1'
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    depends_on:
      cofigserver:
        condition: 'service_healthy'
      loansdb:
        condition: 'service_healthy'
    environment:
      SPRING_APPLICATION_NAME: "loans"
      SPRING_DATASOURCE_URL: "jdbc:mysql://loansdb:3306/loansdb"
    extends:
      file: 'common-config.yml'
      service: 'microservice-eureka-config'

  loans1:
    image: "colince819/loans:v6"
    container_name: loans-ms1
    ports:
      - "8091:8090"
    healthcheck:
      test: 'curl --fail --silent http://localhost:8090/actuator/health/readiness | grep "UP" || exit 1'
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    depends_on:
      cofigserver:
        condition: 'service_healthy'
      loansdb:
        condition: 'service_healthy'
    environment:
      SPRING_APPLICATION_NAME: "loans"
      SPRING_DATASOURCE_URL: "jdbc:mysql://loansdb:3306/loansdb"
    extends:
      file: 'common-config.yml'
      service: 'microservice-eureka-config'

  cards:
    image: "colince819/cards:v6"
    container_name: cards-ms
    ports:
      - "9000:9000"
    healthcheck:
      test: 'curl --fail --silent http://localhost:9000/actuator/health/readiness | grep "UP" || exit 1'
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    depends_on:
      cofigserver:
        condition: 'service_healthy'
      cardsdb:
        condition: 'service_healthy'
    environment:
      SPRING_APPLICATION_NAME: "cards"
      SPRING_DATASOURCE_URL: "jdbc:mysql://cardsdb:3306/cardsdb"
    extends:
      file: 'common-config.yml'
      service: 'microservice-eureka-config'

  gatewayserver:
    image: "colince819/gatewayserver:v2"
    container_name: gatewayserver-ms
    ports:
      - "8072:8072"
    depends_on:
      accounts:
        condition: service_healthy
      cards:
        condition: service_healthy
      loans:
        condition: service_healthy
      loans1:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "gatewayserver"
      SPRING_DATA_REDIS_CONNECT-TIMEOUT: 2s
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      SPRING_DATA_REDIS_TIMEOUT: 1s
    extends:
      file: 'common-config.yml'
      service: 'microservice-eureka-config'

networks:
  eazybank:
    driver: bridge