apiVersion: 1

deleteDatasources: # We are first trying to delete any datasource with the below listed names.
  - name: Prometheus
  - name: Loki
  - name: Tempo

datasources: # Post that, we are trying to create new datasource's with the names and configurations like below.
  - name: Prometheus
    type: prometheus
    uid: prometheus
    url: http://prometheus:9090
    access: proxy
    orgId: 1
    basicAuth: false
    isDefault: false
    version: 1
    editable: true
    jsonData:
      httpMethod: GET
  - name: Tempo # Name of the datasource
    type: tempo # And it is of type tempo
    uid: tempo # The uid I am trying to give to this is tempo
    url: http://tempo:3100 # It is going to start at the port 3100. Grafana is going to interact with tempos using the service name 'tempo' as can be seen in this url.
    access: proxy
    orgId: 1
    basicAuth: false
    isDefault: false
    version: 1
    editable: true
    jsonData:
      httpMethod: GET
      serviceMap:
        datasourceUid: 'prometheus'
  - name: Loki
    type: loki
    uid: loki
    access: proxy
    orgId: 1
    editable: true
    url: http://gateway:3100
    jsonData:
      httpHeaderName1: "X-Scope-OrgID"
      derivedFields:
        - datasourceUid: tempo
          matcherRegex: "\\[.+,(.+),.+\\]"
          name: TraceID
          url: '$${__value.raw}'
    secureJsonData:
      httpHeaderValue1: "tenant1"