package com.get_tt_right.gwserver;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.cloud.gateway.route.RouteLocator;
import org.springframework.cloud.gateway.route.builder.RouteLocatorBuilder;
import org.springframework.context.annotation.Bean;

import java.time.LocalDateTime;

/** Update as of 20/4/2026
 * -------------------------
 * We will see the demo of API Composition pattern with the help of Spring Cloud Gateway so that you will feel comfortable in implementing the same pattern inside your real projects. For this demo we need four different ms's with the names customers, accounts, loans and cards. Along with these four different ms's we need supporting components like EurekaServer and an Edge server which is implemented with the help of Spring Cloud Gateway. We will not build these ms's and supporting components from scratch as we already have them. We will just use them to drive our learning point home. Nothing but on top of what we already have we will make the changes to adopt this API Composition pattern or Gateway Aggregator/Composition pattern.
 * The reason we are not implementing all these ms's and supporting components from scratch is - we already discussed on how to build ms's and supporting components like eureka server and edge/gateway server in the ms's sessions. We also have a bom project with the name eazy-bom. A bom project is a special maven project which is going to help us to define all the ms dependencies and versions in a centralized place. This BOM concept we discussed already in details. Check the getttright-bom pom.xml to quickly understand what is there.
 * If you open the respective ms's, you can be able to see how the BOM project/file is leveraged - check respective individual ms's pom.xml file for how. Ex: accounts ms pom.xml.
 * Now, once you set up these projects and load them as maven projects you can trigger the build and for some reason if you are getting an CE's then there is a very good chance that your common module is not compiled properly and for such cases, while in the common module pom.xml press ctrl 2 times, and you will have a pop-up option inside your intelliJ idea, select the project as common on the RHS dropdown 'project' label and then run the command which is 'mvn clean install -Dmaven.test.skip=true' and this will fix the issue. Basically what will happen the jar or maven will be generated so that my other ms's can leverage it. During the jar generation my maven will try to do the unit testing which is what we are trying to avoid because we will run into some error around the unit testing. On executing this command you should be able to see that the build is successful and the common jar is going to be published into my local maven repo.
 * So, from my local maven repo all my individual ms's  are going to pick/point to this common library. Like this now, when you do the build of you individual ms;s you should not run into any issues - now our set up looks good! At last let's highlight one thing about the lombok annotations - since we are going to use the lombok related annotations inside our ms's please make sure you have installed the lombok related plugin inside your IDE. After that, you can go the setting and search for annotation processing under the compiler and here you need to make sure you have checked the box to enable the annotation processing then click on apply so that the lombok annotations are going to work  without any issues.
 * Like this you should be clear with the set-up of our project. Next we will visualize an explanation of what code we have written in our ms's on a high level so that you will be comfortable about all the code you have inside these m's.
 *
 * Understanding ms's code and set-up
 * -----------------------------------
 * Check respective ms's docstrings to explaore what code is written in them. With all we have discussed in the accounts ms, you should be crisp clear. The similar kind of set-up you should be able to see under the cards which is going to help you to create, read, update and delete card details inside the DB with the help of a mobile number. The same applies for loans ms.
 * At last, we have customer ms with the help of which we can create a brand new customer by giving personal details like name email and mobile number. The flow will always be first we need to create customer details, next by using the same mobile number that we have used to create the customer, we can create records under the accounts, loans and cards. So make sure you have set up these ms's and supporting components inside your local system, then open each and every file and try to what logic has been written.
 * Since we completed the ms's sessions, then understanding most of this code is very easy, and you will be able to complete this activity very quickly. Compared to what we discussed in ms's sessions, here we have introduced a new ms which is customer ms, with this, in total we will be having 4 different ms's inside my project set up. We have done this intentionally so that we can learn and visualize lot many design patterns around the event driven ms's.
 * Now, we will try to start all our ms's and try to create some data so that you will be comfortable and clear around the logic we have written in our ms's. Press a short-cut which is Alt + 8 inside your IntelliJ Idea - this is going to pen the Services tab. Under the Spring Boot, you should be able to see all the entry point classes that you have inside your project. So, instead of the hustle of opening all the spring boot main classes of each individual ms manually, you can always locally start all your ms's from this option/location. In case if you are not seeing this in your ide then mean you will have to open your individual ms's main classes manually and start them one by one. Once you start them then your service details will be shown in the services tab. Like this from the next time onwards you don't have to start the ms's one by one manually from your respective main class files. This is a feature which is available inside intelliJ ultimate only - in case if you are using the community version then your need to start the ms's one by one manually from your respective spring boot application main class files.
 * First, we need to start the eurekaserver because all my ms's are going to register with the eurekaserver - once my eurekaserver is started at the port 8070, I am going to start accounts application, followed by cards, customer and at last start the loans application. Like this all my services are started at various port numbers. Now, at last you can start your gatewayserver application. This is the order you need to start your services. Now, you can try to open your eureka dashboard and inside this you should be able to see that all the services are registered and this should confirm to you that your eurekaserver setup and your ms's set up is working fine. Before we try to test these API's first lets see something obout our logs in the console. If you closely look at the logs, all of them are being displayed using various colors in a predefined format that we have defined inside our application.yaml files of the respective services. You can be able to see that first we are trying to display the timestamp in a mentioned/defined format in green color. Then followed by the log level in Blue color. Followed by thread details in red color. Followed by the actual logger and message in yellow and white color by default as can be seen in the console. This is going to add some fun to my work instead of debugging and searching and looking at some boring logs, we are trying to add some colors to our logs.
 * Now next in postman you can go ahead and test all the services - check the collection EventDriven Microservices. Under the Customer folder in the collection, we have 4 different requests which are going to help us to create, read, update and delete customer details. If you open the create customer request which is a POST API and the path that we are trying to invoke is - '/eazybank/customer/api/create'. You may have a question like wher did you mention the hist name, port number? haha! To avoid mentioning the host name and port number for each and every request under the collection 'EventDriven Microservices' >> Scripts tab, I have defined some scripts. Under the Pre-request option/section I have defined some JavaScript code i.e.,
 pm.request.url.protocol="http";
 pm.request.url.host="localhost";
 pm.request.url.port="8072";
 *
 * pm stands for postman. So, using this pm object I am trying to invoke request.url.protocol/host/port and assigning the respective value. 8072 port belongs to my gatewyaserver application. Since my gatewayserver application is going to act as an edgeserver for my ms's then we are always going to use our gatewayserver details to send the request. If you open the class with the name GatewayserverApplication you should be able to see some routing related configurations. So, if someone tries to make a request to the api with the regex/prefix as '/eazybank/customer/**' then we will forward the request to the customer ms. Like this my gatewayserver is going to ask the eurekaserver to load balance and forward the request to one of the instances of Customer ms as can be seen in the configuration i.e., "lb://CUSTOMER". After that prefix/regex whatever comes in place of the ** the same we will try to forward to the actual ms as can be seen picked in the configurations i.e., "/eazybank/customer/(?<segment>.*)". All these configurations we discussed in details in the ms's sessions - you can revisit that in case of any doubts.
 * Now you can fire the actual request and test to verify that everything/our written business logic is as expected. So fire the requests in the order - create >> fetch to verify >>  then update >> fetch to verify >> delete >> fetch to verify. When you delete my customer got soft deleted - to verify the same you can go ahead and query the DB. To query the DB you don't have to open the browser or h2 console, there is a feature inside intelliJ ultimate. What you need to do is - open the application.yaml file of for example customer ms and there, on the LHS just before the DB property you will be able to see a DB icon - you can click on the + symbol on it and this should take you to a new window and there you should have all your connection details pre-populated - test the connection and it should successfully pass. Incase you encounter any issues then make sure you have installed the drivers related to the H2 DB - IntelliJ is smart enough to guide you on this as somewhere on that window you are going to have an option to install the respective h2 drivers and once this is done you should be able to successfully complete this test connection. Finally, you can click on Apply and OK and with that you should be having a new DB connection when you click on the DB icon on the RHS of your IDE related to the customer ms. Same drill applies for the other ms's i.e., accounts, cards and loans. Now with this you should be able to query your respective DB happily to perform your test verifications. Like this, if you check for the active switch column on the selected record, it is marked as false and this should give a confirmation that our code/business logic is working perfectly. As a next step, test and verify the other ms's requests i.e, accounts, cards and loans just like we have done for customer ms. Please make sure you are using the same mobile number across ms's as this the only common data of a customer across all ms's.
 * Without following a common mobile number we can't fetch the data from all the ms's. For update account, we saw earlier on tha we are only allowed to update the account type and branch address. So in our tests, you can update the branch address to lets say '124 Main Street, New York' from '123 Main Street, New York'. For the delete operation we need to provide the account number as an input. In the similar fashion you can test the loans and cards related ms's and verify that the business logic we have written is proper as expected. Since inside the h2 db configurations we have mentioned to use the file - behind the scenes what h2 db will do is it will try to create various files inside your user folder - there, you will see their are many files with the extention as '.db'. We have accounts related file, followed by cards, customer, as well as loans. As long as these files are not deleted you will be able to see the saved/updated data even after the restart of your services.Anytime if you want to start from scratch with brand-new data or with a brand new h2 db you just have to navigate to your user folder and delete all those .db files. Next, we will be implementing the api composition pattern inside the gatewayserver.
 *
 * Implementing API Composition Pattern using Spring Cloud Gateway.
 * -----------------------------------------------------------------
 * We are trying to solve the challenge of cross-service queries with the help of API Composition pattern. Whenever we want to implement API composition pattern as we discussed previously, we will have 3 different options 1. Client applications like front-end web applications - they themselves acts as an API composer, they are going to invoke all the required respective ms's to fetch the data. Once the data is fetched, on the UI side itself, they are going to combine the data and display it on the webpage. For this option we are not going to see any demo because it requires knowledge on Angular or React and since it is out of the scope of our sessions you can happily ignore this option to give the demo. The second option is with the help of API Gateway which acts as an API composer. This is the option we are going to see the demo of inside this activity. We will visualize the implementation on this. The last option that we have is a standalone service itself is going to act as an API composer - this we in details already visualized and discussed in our ms's sessions where we had accounts ms as an API composer. We implemented this with the help of Open-Feign client. Inside the accounts ms, under controller package we had a controller with the name CustomerController - anyone who need to fetch the accounts , loans and cards details of the customer of the customer they used to invoke the api 'fetchCustomerDetails' in Customer controller by passing a mobile number of that customer as input. From the controller, we called a method which is fetchCustomerDetails which is present inside the CustomerServiceImpl implementation class. Here, we have logic to invoke various ms's (For ex: for loans data we are trying to invoke the loans api with the help of feign client, same drill for cards api invocation whereas for the accounts related data we are trying to load the data from the accounts DB since all this logic is present inside the accounts ms then it is going to be a simple DB call) - once we have accounts, cards and loans information, we are trying to set that data inside a CustomerDetailsDto object and the same we are trying to send as a response to the client application. Since we already saw this in our ms's sessions, this should be very straight forward for you because we discussed and visualized all this in details in our ms's sessions. This is how we implement API composition pattern from one of the ms's itself - in our case accounts ms.
 * Now, inside my gatewayserver I am going to create a new package - dto. Reason - I want to send the response to the client application by aggregating/composing all the required data from the respective ms's. That's why I need to create the dto's representing data from multiple ms's. So Inside this package I am going to create a new class with the name CustomerDto - check it out for docstring. The next dto class we are creating is AccountsDto - Check its docstring. In the similar lines I am going to create another dto class - CardsDto and LoansDto. Now we have various Dto classes which are going to help us to hold data from various respective ms's. For example, CustomerDto class is going to hold data from customer ms, CardsDto class is going to hold data from cards ms and so on. But we can't send the data to the client application individually, we want to compose all this data into a single object and that is what we will send as a response to the client application. For this, we will create one more dto class with the name CustomerSummeryDto - check its docstring. This is going to be the final object which is going to be sent to the client application so that it is going to get an aggregated response from all the four different ms's. With this now, we have created all the required dto classes.
 * Next, I need to provide details to my gatewayserver on how to invoke my individual ms's. For the same I am going to create a new package i.e., service.client. Inside this package I am going to create an interface with the name CustomerSummeryClient - check its docstring for details. The name of this interface can be anything btw, but I have chosen CustomerSummeryClient because we are trying to provide customer summery details. As of now we have developed the interface - CustomerSummaryClient where we have build various abstract methods conveying the metadata information about all the ms's that my gateway has to invoke. Apart from this metadata information my gateway also should know what is the root base url like what is the host name, port number. Along with this root base url, we are also expecting our gatewayserver to invoke these APIs parallelly in a non-blocking functional state. For this kind of parallel invocation we can't leverage open-feign client the reason being open-feign client does not support reactive programming model. That's why instead of the open-feign client we are going to use the web-client which is another component inside the Spring ecosystem which can be leveraged whenever we are looking to invoke APIs in a non-blocking style and parallely. So, to provide base root url and to create the configuration of webclient what we need to do is to create one more package with the name config - inside this package create a java class with the name ClientConfig. - Check out this class for docstring. As a next step, I need to create a new class which is reponsible to invoke all the respective ms's and finally aggregate/compose the response from the ms's. For this, I will create a new package with the name 'handler' and inside this I am going to create a new class with the name 'CustomerCompositeHandler' - check its docstring.
 * Whenever someone makes an API call, we want the logic of fetchCustomerSummary inside CustomerCompositeHandler to be invoked. As discussed at the end of the docstring of CustomerCompositeHandler, in reactive applications, we can't build the REST APIs by using RestController, like we can't put the @RestController annotation on top of CustomerCompositeHandler class and make the entire logic of fetchCustomerSummary to be executed. Instead, inside the reactive applications, we need to define functions which are capable of handling a specific route request. That's why what we are going to do is - we are going to create a new package with the name 'router' and inside this package we are going to create a new java class with the name 'CustomerCompositeRouter' - check its docstring.
 * With this, we are done with all the coding changes to implement API Composition pattern inside the gatewayserver. So, do a build and once it is completed we can try to start all our services. Now, you can go to the postman and create new data/records for each of the ms's again. why? haha whatever data that we had created previously it is soft deleted and we can't use that data/that record. That's why create the customer - POST request under customer collection - with the same mobile number. Next, create a customer account - POST request under accounts collection - using the same mobile number. Next, create a customer loan - POST request under loans collection - using the same mobile number. Next, create a customer card - POST request under cards collection - using the same mobile number. Like this now, we have data stored in multiple ms's. Now, with the help of gatewayserver collection, we are going to invoke an API/request i.e., fetchCustomerSummary which has the path/url of '/api/composite/fetchCustomerSummary?mobileNumber=3254537622' and as you can see it has the query param of 'mobileNumber' - so same mobile number you need to pass. Hurrey! we are getting the response successfully - we are getting the response within 66 milliseconds. This is going to take more time if you have implemented API Composition pattern in a normal ms with the help of feign client like we did is our ms's discussions. Reason - Feign client will not use Reactive programming and with that all the ms's invocations - they are going to happen sequentially 1 by 1. But in our case/scenario this time around the response TAT time is going to be better because we have implemented the API Composition pattern inside the Spring Cloud gateway.
 * Like this, with all we have discussed you should now be crisp clear on how we have overcome the challenge of Cross-Service Queries with the help of API Composition Pattern. Of course this pattern has certain limitations like, this pattern can only be used for the read operations and for smaller applications only. Whereas for bigger enterprise applications, API Composition pattern may not help you, and you may need to consider an advanced pattern referred to as CQRS pattern which we will discuss in details in the coming sessions.
 *
 * * * */


@SpringBootApplication
public class GatewayserverApplication {

    public static void main(String[] args) {
        SpringApplication.run(GatewayserverApplication.class, args);
    }

    @Bean
    public RouteLocator eazyBankRouteConfig(RouteLocatorBuilder routeLocatorBuilder) {
        return routeLocatorBuilder.routes()
                .route(p -> p
                        .path("/eazybank/customer/**")
                        .filters(f -> f.rewritePath("/eazybank/customer/(?<segment>.*)", "/${segment}")
                                .addResponseHeader("X-Response-Time", LocalDateTime.now().toString()))
                        .uri("lb://CUSTOMER"))
                .route(p -> p
                        .path("/eazybank/accounts/**")
                        .filters(f -> f.rewritePath("/eazybank/accounts/(?<segment>.*)", "/${segment}")
                                .addResponseHeader("X-Response-Time", LocalDateTime.now().toString()))
                        .uri("lb://ACCOUNTS"))
                .route(p -> p
                        .path("/eazybank/loans/**")
                        .filters(f -> f.rewritePath("/eazybank/loans/(?<segment>.*)", "/${segment}")
                                .addResponseHeader("X-Response-Time", LocalDateTime.now().toString()))
                        .uri("lb://LOANS"))
                .route(p -> p
                        .path("/eazybank/cards/**")
                        .filters(f -> f.rewritePath("/eazybank/cards/(?<segment>.*)", "/${segment}")
                                .addResponseHeader("X-Response-Time", LocalDateTime.now().toString()))
                        .uri("lb://CARDS")).build();


    }


}
