services:
  rabbit:
    image: rabbitmq:4.0-management
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s
    extends:
      file: 'common-config.yml'
      service: 'network-deploy-service'

  cofigserver:
    image: "colince819/configserver:v1"
    container_name: configserver-ms
    ports:
      - "8071:8071"
    depends_on:
      rabbit:
        condition: service_healthy
    healthcheck:
      test: 'curl --fail --silent http://localhost:8071/actuator/health/readiness | grep "UP" || exit 1'
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: 'common-config.yml'
      service: 'microservice-base-config'

  accounts:
    image: "colince819/accounts:v2"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    depends_on:
     cofigserver:
       condition: 'service_healthy'
    extends:
      file: 'common-config.yml'
      service: 'microservice-configserver-config'

    environment:
      SPRING_APPLICATION_NAME: "accounts"

  loans:
    image: "colince819/loans:v2"
    container_name: loans-ms
    ports:
      - "8090:8090"
    depends_on:
      cofigserver:
        condition: 'service_healthy'
    extends:
      file: 'common-config.yml'
      service: 'microservice-configserver-config'
    environment:
      SPRING_APPLICATION_NAME: "loans"


  cards:
    image: "colince819/cards:v2"
    container_name: cards-ms
    ports:
      - "9000:9000"
    depends_on:
      cofigserver:
        condition: 'service_healthy'
    extends:
      file: 'common-config.yml'
      service: 'microservice-configserver-config'
    environment:
      SPRING_APPLICATION_NAME: "cards"

networks:
  eazybank:
    driver: bridge