spring:
  application:
    name: "eurekaserver"
  config:
    import: 'optional:configserver:http://localhost:8071'

management:
  endpoints:
    web:
      exposure:
        include: '*'
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

logging:
  level:
    com:
      get_tt_right:
        eurekaserver: "DEBUG"
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"