# Everything we copied from Accounts microservice except the port number.
server:
  port: 8090
spring:
  application:
    name: "loans"
  datasource:
    url: jdbc:mysql://localhost:3309/loansdb
    username: 'root'
    password: 'root'
  sql:
    init:
      mode: always
  jpa:
    show-sql: true
  config:
    import: "optional:configserver:http://localhost:8071"
  profiles:
    active:
      - "qa"
  rabbitmq:
    host: 'localhost'
    port: '5672'
    username: 'guest'
    password: 'guest'

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    shutdown:
      enabled: true
  info:
    env:
      enabled: true

endpoints:
  shutdown:
    enabled: true

info:
  app:
    name: "loans"
    description: "Eazy Bank Loans SApplication"
    version: "1.0.0"